package com.lagauchita.modelo;
// Generated 14/11/2012 09:21:03 by Hibernate Tools 3.2.1.GA



/**
 * Pasajero generated by hbm2java
 */
public class Pasajero  implements java.io.Serializable {


     private int dni;
     private String apellido;
     private String nombre;
     private String direccion;

    public Pasajero() {
    }

	
    public Pasajero(int dni) {
        this.dni = dni;
    }
    public Pasajero(int dni, String apellido, String nombre, String direccion) {
       this.dni = dni;
       this.apellido = apellido;
       this.nombre = nombre;
       this.direccion = direccion;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


